Feature/UI design/chat detail UI
Rayeen-Software-Solutions/roomzy pull request #20
Opened 2024-09-11 08:03 UTC by rabia543

2024-09-14 21:27 UTC, Dilshad440 requested changes

2024-09-14 21:27 UTC, Dilshad440 commented on lib/core/constant/route_const.dart
> +  static const String chatDetail = '/chat_detail';
change it into chat-listing as it is standard naming convention of page

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_detail/controller/chat_detail_controller.dart
> +    update();
If you are using OBX i don;t think you need to update controller, as message variable is RX variable so OBX will listen whenever it changes

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_detail/page/chat_detail_screen.dart
> +            children: <Widget>[
Create a common utils file called message utils... and this utils stuff over there....

The reason is simple as that, controller only hold the logic part, UI should not be written in the controller... and this is a dialog/bottomsheet so you can move into utils, refer other utils like common utils files for reference

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_detail/page/chat_detail_screen.dart
> +                  Navigator.pop(context);
Instead of  Navigator.pop(context) it should be Get.back()

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_detail/page/chat_detail_screen.dart
> +      imageQuality: 70,
We already have common utils for image picker

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_detail/page/chat_detail_screen.dart
> +          final client = http.Client();
Remove http and use rest client, check restclient file for more details.

`you can use RestClient.getInstance();`

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_detail/page/chat_detail_screen.dart
> +    final result = await FilePicker.platform.pickFiles(
This all method should be in controller
handleFileSelection()
handleImageSelection()
handleImageSelection()

this kind of method should be in controller as it will interact with logic and api

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_detail/page/chat_detail_screen.dart
> +            color: Colors.white,
Move this statusMsgIcon() method into utils file

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_listing/page/chat_listing_screen.dart
> +                    controller.cancelSearch(isClearText: false);
No need gesture detector here CommonListTileElement have properties onTap you can use the same

2024-09-14 21:27 UTC, Dilshad440 commented on lib/src/feature/chat/chat_listing/page/chat_listing_screen.dart
> -          onTap: () {
Why you removed gesture detector here, it is used to hide the keyboard and clear textfield text

2024-09-15 04:40 UTC, DilshadAlam98 commented on pubspec.yaml
> +  bubble: ^1.2.1
Bublle wouldn't be needed for chat UI

2024-09-16 18:05 UTC, closed without merging